name: Bug report
description: Report a defect with reproducible steps
labels: ["type:bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: build_hash
    attributes:
      label: Build hash / commit
  - type: input
    id: platform
    attributes:
      label: Browser/device
