name: Content request
description: Bible/content tuning request
labels: ["type:balance", "area:content"]
body:
  - type: textarea
    id: request
    attributes:
      label: Requested content change
    validations:
      required: true
  - type: input
    id: ids
    attributes:
      label: IDs / sheets impacted
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
