name: Feature request
description: Propose a new feature or improvement
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact / tradeoffs
